### ISSUE TITLE
Difference between official(?) plugin and this one

### ISSUE THREAD

**Issue by Loki-Afro** [IntershopCommunicationsAG/sonarqube-gradle-plugin#6]
Where is the difference between this plugin and the official one?

The official is `com.intershop.build:intershop-sonar-plugin:3.0.1` noted here: https://support.intershop.com/kb/index.php/Display/Q27279

**Comment by m-raab** [comment]
This is the replacement for all previous Intershop SonarQube plugins. Our new Gradle Tools version 2.11 does not longer contain a SonarQube plugin. 
There will be a new documentation for Gradle Tools 2.11 with more details after the release announcement.
